site_name: Sistemi Interattivi - NTA
site_url: https://ntngrillo.github.io/test/
site_description: My Fabacademy 2019 site

site_author: Antonio Grillo

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
# extra:
#   social: #Here I've added my social channel
#     - type: "github"
#       link: "https://github.com/antoniogrillo"
#     - type: "twitter"
#       link: "https://twitter.com/ntngrillo"
#     - type: "linkedin"
#       link: "https://www.linkedin.com/in/grilloantonio"
#     - type: "instagram"
#       link: "https://www.instagram.com/ntngrillo80/"

plugins:
  - search:
  # - tags:
  #     tags_file: tags.md
  - blog:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"

markdown_extensions:
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - extra
  - smarty
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: contenu
      permalink: true
      baselevel: 2

# nav:
#   - Home: index.md
#   #- Code Docs:
#    # - Java: coding/my-first-java-file.md
#   #- About:
#    # - Current Projects: about/projects.md
#     #- About Me: about/about.md
#     #- Childhood: about/childhood.md
#   #- Tags: tags.md
#   - Blog:
#     - blog/index.md
